sudo: false
language: node_js
services:
  - docker
addons:
  hosts:
    - petstore.swagger.io 
matrix:
  include:
    - node_js: "10"
      script:
        - ./node_modules/.bin/grunt && istanbul report text && ( cat coverage/lcov.info | $(npm get prefix)/bin/coveralls || true ) && rm -rf coverage
    - node_js: "8"
    - node_js: "6"
before_script:
  - docker pull swaggerapi/petstore
  - docker run -d -e SWAGGER_URL=http://petstore.swagger.io -e SWAGGER_BASE_PATH=/v2 -p 80:8080 swaggerapi/petstore
  - npm install -g istanbul coveralls
